/**
 * The Hugeicons glyphs the app uses, in one place, so the whole UI draws from
 * one vocabulary. Import icons from here, not from the package directly.
 */
export {
  Alert02Icon as WarningIcon,
  ArrowDown01Icon as ChevronDownIcon,
  ArrowLeft01Icon as BackIcon,
  ArrowRight01Icon as ChevronRightIcon,
  ArrowRight01Icon as ForwardIcon,
  BrowserIcon,
  Cancel01Icon as CloseIcon,
  CheckmarkCircle02Icon as SuccessIcon,
  CodeIcon as DevToolsIcon,
  CommandIcon,
  Copy01Icon as CopyIcon,
  CssFile01Icon as CssIcon,
  Delete02Icon as DeleteIcon,
  File01Icon as FileIcon,
  FlashIcon as LiveIcon,
  FloppyDiskIcon as SaveIcon,
  Folder01Icon as FolderIcon,
  FolderOpenIcon,
  GitCompareIcon as DiffIcon,
  Globe02Icon as GlobeIcon,
  Html5Icon as HtmlIcon,
  InformationCircleIcon as InfoIcon,
  JavaScriptIcon as JsIcon,
  Layers01Icon as OverridesIcon,
  LinkSquare02Icon as ExternalLinkIcon,
  MagicWand01Icon as PrettifyIcon,
  PuzzleIcon as IframeIcon,
  RefreshIcon as ReloadIcon,
  Search01Icon as SearchIcon,
  Settings02Icon as SettingsIcon,
  SidebarLeftIcon,
  SourceCodeIcon as ExplorerIcon,
  SparklesIcon,
  Tick02Icon as CheckIcon,
  LayoutRightIcon as PreviewIcon,
} from '@hugeicons/core-free-icons';
