/**
 * The Hugeicons glyphs the app uses, in one place, so the whole UI draws from
 * one vocabulary. Import icons from here, not from the package directly.
 */
export {
  Alert02Icon as WarningIcon,
  AlertCircleIcon as ErrorIcon,
  ApiIcon as ResponseIcon,
  AppWindowIcon as PreviewIcon,
  ArrowDataTransferHorizontalIcon as CorsIcon,
  ArrowDataTransferVerticalIcon as NetworkIcon,
  ArrowDown01Icon as ChevronDownIcon,
  ArrowDown02Icon as FrameReceivedIcon,
  ArrowLeft01Icon as BackIcon,
  ArrowLeftRightIcon as JumpIcon,
  ArrowRight01Icon as ChevronRightIcon,
  ArrowRight01Icon as ForwardIcon,
  ArrowUp02Icon as FrameSentIcon,
  BookmarkAdd02Icon as SaveActionIcon,
  BrowserIcon,
  Cancel01Icon as CloseIcon,
  CheckmarkCircle02Icon as SuccessIcon,
  Clock01Icon as DelayIcon,
  CodeFolderIcon as SourceRootIcon,
  CodeIcon as DevToolsIcon,
  CommandIcon,
  CommandLineIcon as ConsoleIcon,
  Copy01Icon as CopyIcon,
  CpuIcon as WorkerIcon,
  CssFile01Icon as CssIcon,
  CubeIcon as StackIcon,
  DashboardSpeed01Icon as ThrottleIcon,
  Delete02Icon as DeleteIcon,
  Download04Icon as DownloadIcon,
  EraserIcon as ClearValueIcon,
  File01Icon as FileIcon,
  FileCodeIcon as CodeFileIcon,
  FileExportIcon as ExportIcon,
  FileImportIcon as ImportIcon,
  FileLockedIcon as SourceFileIcon,
  FilterHorizontalIcon as FilterIcon,
  FilterIcon as RulesIcon,
  FlashIcon as LiveIcon,
  FloppyDiskIcon as SaveIcon,
  Folder01Icon as FolderIcon,
  FolderOpenIcon,
  GitCompareIcon as DiffIcon,
  Globe02Icon as GlobeIcon,
  HierarchyIcon as TreeViewIcon,
  Html5Icon as HtmlIcon,
  InformationCircleIcon as InfoIcon,
  JavaScriptIcon as JsIcon,
  Layers01Icon as OverridesIcon,
  Link01Icon as LinkIcon,
  LinkSquare02Icon as ExternalLinkIcon,
  LockIcon,
  MagicWand01Icon as PrettifyIcon,
  NewReleasesIcon as WhatsNewIcon,
  PackageIcon as LibraryIcon,
  PauseCircleIcon as BreakpointIcon,
  PauseIcon,
  PencilEdit02Icon as EditIcon,
  PinIcon,
  PlayIcon as RunIcon,
  PlayListIcon as ActionsIcon,
  PlusSignIcon as AddIcon,
  PuzzleIcon as IframeIcon,
  ReactIcon as JsxIcon,
  RefreshIcon as ReloadIcon,
  Search01Icon as SearchIcon,
  SentIcon as SendIcon,
  Settings02Icon as SettingsIcon,
  SidebarLeftIcon,
  SlidersHorizontalIcon as HeadersIcon,
  SourceCodeIcon as ExplorerIcon,
  SparklesIcon,
  SquareArrowDownLeftIcon as DockIcon,
  SquareArrowUpRight02Icon as PopOutIcon,
  Tag01Icon as NameIcon,
  Tick02Icon as CheckIcon,
  TypescriptIcon as TsIcon,
  UnavailableIcon as BlockIcon,
  WifiDisconnected01Icon as FailIcon,
} from '@hugeicons/core-free-icons';
