/**
 * The Hugeicons glyphs the app uses, in one place, so the whole UI draws from
 * one vocabulary. Import icons from here, not from the package directly.
 */
export {
  Alert02Icon as WarningIcon,
  AlertCircleIcon as ErrorIcon,
  AppWindowIcon as PreviewIcon,
  ArrowDown01Icon as ChevronDownIcon,
  ArrowLeft01Icon as BackIcon,
  ArrowRight01Icon as ChevronRightIcon,
  ArrowRight01Icon as ForwardIcon,
  BrowserIcon,
  Cancel01Icon as CloseIcon,
  CheckmarkCircle02Icon as SuccessIcon,
  CodeIcon as DevToolsIcon,
  CommandIcon,
  CommandLineIcon as ConsoleIcon,
  Copy01Icon as CopyIcon,
  CssFile01Icon as CssIcon,
  Delete02Icon as DeleteIcon,
  Download04Icon as DownloadIcon,
  File01Icon as FileIcon,
  FlashIcon as LiveIcon,
  FilterHorizontalIcon as FilterIcon,
  FloppyDiskIcon as SaveIcon,
  Folder01Icon as FolderIcon,
  FolderOpenIcon,
  GitCompareIcon as DiffIcon,
  Globe02Icon as GlobeIcon,
  Html5Icon as HtmlIcon,
  InformationCircleIcon as InfoIcon,
  JavaScriptIcon as JsIcon,
  Layers01Icon as OverridesIcon,
  LinkSquare02Icon as ExternalLinkIcon,
  MagicWand01Icon as PrettifyIcon,
  NewReleasesIcon as WhatsNewIcon,
  PencilEdit02Icon as EditIcon,
  PinIcon,
  PlayIcon as RunIcon,
  PlusSignIcon as AddIcon,
  PuzzleIcon as IframeIcon,
  RefreshIcon as ReloadIcon,
  Search01Icon as SearchIcon,
  Settings02Icon as SettingsIcon,
  SidebarLeftIcon,
  SourceCodeIcon as ExplorerIcon,
  SparklesIcon,
  Tag01Icon as NameIcon,
  Tick02Icon as CheckIcon,
} from '@hugeicons/core-free-icons';
