export {
  useTabStore,
  selectActiveTab,
  selectActivePage,
  selectActiveSource,
  isPageDirty,
  PAGE_SCOPES,
  type TabMeta,
  type SourceTab,
  type PageTab,
  type PageKind,
  type PageTabOf,
  type PageScope,
  type RulePageDraft,
  type DiffMode,
} from './model/store';
export {
  newTabId,
  onTabEdited,
  createTabModel,
  createSourceModel,
  getTabModel,
  getTabBase,
  setTabBase,
  markTabSaved,
  replaceTabText,
  disposeTabModel,
} from './model/models';
