import * as monaco from 'monaco-editor';
import { THEME } from './constants';

/**
 * Monaco needs hex colors; these approximate the OKLCH tokens in
 * app/styles/tokens.css (surface-editor, line, fg-subtle, accent, live…).
 */
const c = {
  bg: '#0d0d10',
  raised: '#18181c',
  overlay: '#1a1a1f',
  line: '#ffffff12',
  fg: '#ececef',
  muted: '#a1a1ad',
  subtle: '#5e5e6b',
  accent: '#ff8a3d',
  live: '#c9f24b',
  info: '#7cc4fa',
  warning: '#f2c76b',
  danger: '#f2685c',
};

export function defineThemes(): void {
  monaco.editor.defineTheme(THEME, {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'e4e4ea' },
      { token: 'comment', foreground: '5e6373', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'c4a1ff' },
      { token: 'string', foreground: 'b5e38a' },
      // A JSON key reads apart from its value, as keys in the console do.
      { token: 'string.key.json', foreground: '7dcfff' },
      { token: 'string.escape', foreground: 'f2c76b' },
      { token: 'number', foreground: 'ff9e64' },
      { token: 'regexp', foreground: 'f7768e' },
      { token: 'type.identifier', foreground: '7dcfff' },
      { token: 'identifier', foreground: 'e4e4ea' },
      { token: 'delimiter', foreground: '9aa0ae' },
      { token: 'delimiter.bracket', foreground: 'c0c3cc' },
      { token: 'tag', foreground: 'f7768e' },
      { token: 'metatag', foreground: 'f7768e' },
      { token: 'attribute.name', foreground: 'f2c76b' },
      { token: 'attribute.value', foreground: 'b5e38a' },
      { token: 'attribute.value.number', foreground: 'ff9e64' },
      { token: 'attribute.value.unit', foreground: 'ff9e64' },
      { token: 'attribute.value.hex', foreground: 'ff9e64' },
    ],
    colors: {
      'editor.background': c.bg,
      'editor.foreground': c.fg,
      'editorLineNumber.foreground': c.subtle,
      'editorLineNumber.activeForeground': c.muted,
      'editor.lineHighlightBackground': '#ffffff07',
      'editor.lineHighlightBorder': '#00000000',
      'editor.selectionBackground': '#ff8a3d40',
      'editor.inactiveSelectionBackground': '#ff8a3d24',
      'editor.selectionHighlightBackground': '#ff8a3d1f',
      'editor.wordHighlightBackground': '#ffffff10',
      'editor.findMatchBackground': '#f2c76b55',
      'editor.findMatchHighlightBackground': '#f2c76b26',
      'editorCursor.foreground': c.accent,
      'editorIndentGuide.background1': '#ffffff0a',
      'editorIndentGuide.activeBackground1': '#ffffff24',
      'editorWhitespace.foreground': '#ffffff1a',
      'editorBracketMatch.background': '#ffffff12',
      'editorBracketMatch.border': '#ffffff30',
      'editorGutter.background': c.bg,
      'editorOverviewRuler.border': '#00000000',
      'editorWidget.background': c.overlay,
      'editorWidget.border': c.line,
      'editorSuggestWidget.background': c.overlay,
      'editorSuggestWidget.border': c.line,
      'editorSuggestWidget.selectedBackground': '#ffffff12',
      'editorHoverWidget.background': c.overlay,
      'editorHoverWidget.border': c.line,
      'input.background': c.raised,
      'input.border': c.line,
      'focusBorder': '#ff8a3d80',
      'scrollbar.shadow': '#00000000',
      'scrollbarSlider.background': '#ffffff14',
      'scrollbarSlider.hoverBackground': '#ffffff22',
      'scrollbarSlider.activeBackground': '#ffffff30',
      'minimap.background': c.bg,
      'diffEditor.insertedTextBackground': '#c9f24b1f',
      'diffEditor.removedTextBackground': '#f2685c26',
      'diffEditor.insertedLineBackground': '#c9f24b0f',
      'diffEditor.removedLineBackground': '#f2685c14',
      'diffEditorGutter.insertedLineBackground': '#c9f24b1a',
      'diffEditorGutter.removedLineBackground': '#f2685c1f',
      'diffEditor.diagonalFill': '#ffffff0a',
      'editorError.foreground': c.danger,
      'editorWarning.foreground': c.warning,
      'editorInfo.foreground': c.info,
    },
  });
}
