/** CDP's network, page, runtime, log, service worker, target and browser domains, as the protocol spells their commands and events. */
export const CDP_TARGETS = {
  Network: {
    emulateNetworkConditions: 'Network.emulateNetworkConditions',
    enable: 'Network.enable',
    getRequestPostData: 'Network.getRequestPostData',
    getResponseBody: 'Network.getResponseBody',
    setBypassServiceWorker: 'Network.setBypassServiceWorker',
    setCacheDisabled: 'Network.setCacheDisabled',
    // Events
    loadingFailed: 'Network.loadingFailed',
    loadingFinished: 'Network.loadingFinished',
    requestServedFromCache: 'Network.requestServedFromCache',
    requestWillBeSent: 'Network.requestWillBeSent',
    requestWillBeSentExtraInfo: 'Network.requestWillBeSentExtraInfo',
    responseReceived: 'Network.responseReceived',
    responseReceivedExtraInfo: 'Network.responseReceivedExtraInfo',
    webSocketClosed: 'Network.webSocketClosed',
    webSocketCreated: 'Network.webSocketCreated',
    webSocketFrameError: 'Network.webSocketFrameError',
    webSocketFrameReceived: 'Network.webSocketFrameReceived',
    webSocketFrameSent: 'Network.webSocketFrameSent',
    webSocketHandshakeResponseReceived: 'Network.webSocketHandshakeResponseReceived',
    webSocketWillSendHandshakeRequest: 'Network.webSocketWillSendHandshakeRequest',
  },
  Page: {
    addScriptToEvaluateOnNewDocument: 'Page.addScriptToEvaluateOnNewDocument',
    captureScreenshot: 'Page.captureScreenshot',
    createIsolatedWorld: 'Page.createIsolatedWorld',
    enable: 'Page.enable',
    getFrameTree: 'Page.getFrameTree',
    getLayoutMetrics: 'Page.getLayoutMetrics',
    navigate: 'Page.navigate',
    reload: 'Page.reload',
    getResourceContent: 'Page.getResourceContent',
    removeScriptToEvaluateOnNewDocument: 'Page.removeScriptToEvaluateOnNewDocument',
    setBypassCSP: 'Page.setBypassCSP',
    // Events
    frameAttached: 'Page.frameAttached',
    frameDetached: 'Page.frameDetached',
    frameNavigated: 'Page.frameNavigated',
    frameStoppedLoading: 'Page.frameStoppedLoading',
    loadEventFired: 'Page.loadEventFired',
  },
  Runtime: {
    addBinding: 'Runtime.addBinding',
    removeBinding: 'Runtime.removeBinding',
    disable: 'Runtime.disable',
    discardConsoleEntries: 'Runtime.discardConsoleEntries',
    enable: 'Runtime.enable',
    callFunctionOn: 'Runtime.callFunctionOn',
    evaluate: 'Runtime.evaluate',
    getProperties: 'Runtime.getProperties',
    queryObjects: 'Runtime.queryObjects',
    releaseObjectGroup: 'Runtime.releaseObjectGroup',
    runIfWaitingForDebugger: 'Runtime.runIfWaitingForDebugger',
    // Events
    bindingCalled: 'Runtime.bindingCalled',
    consoleAPICalled: 'Runtime.consoleAPICalled',
    exceptionThrown: 'Runtime.exceptionThrown',
    executionContextCreated: 'Runtime.executionContextCreated',
    executionContextDestroyed: 'Runtime.executionContextDestroyed',
    executionContextsCleared: 'Runtime.executionContextsCleared',
  },
  Log: {
    clear: 'Log.clear',
    disable: 'Log.disable',
    enable: 'Log.enable',
    // Events
    entryAdded: 'Log.entryAdded',
  },
  ServiceWorker: {
    disable: 'ServiceWorker.disable',
    enable: 'ServiceWorker.enable',
    unregister: 'ServiceWorker.unregister',
    // Events
    workerRegistrationUpdated: 'ServiceWorker.workerRegistrationUpdated',
    workerVersionUpdated: 'ServiceWorker.workerVersionUpdated',
  },
  Target: {
    attachToTarget: 'Target.attachToTarget',
    detachFromTarget: 'Target.detachFromTarget',
    getTargetInfo: 'Target.getTargetInfo',
    setAutoAttach: 'Target.setAutoAttach',
    setDiscoverTargets: 'Target.setDiscoverTargets',
    activateTarget: 'Target.activateTarget',
    closeTarget: 'Target.closeTarget',
    createTarget: 'Target.createTarget',
    getTargets: 'Target.getTargets',
    // Events
    attachedToTarget: 'Target.attachedToTarget',
    detachedFromTarget: 'Target.detachedFromTarget',
    targetCreated: 'Target.targetCreated',
    targetDestroyed: 'Target.targetDestroyed',
    targetInfoChanged: 'Target.targetInfoChanged',
  },
  Browser: {
    getVersion: 'Browser.getVersion',
  },
} as const;
